### ISSUE TITLE
trtexec转换onnx出现segmentation fault！

### ISSUE THREAD

**Issue by Jaiy** [MAhaitao999/Yolov3_Dynamic_Batch_TensorRT_Triton#2]
您好，感谢您的工程！按照操作对“修改了网络结构及输入图片尺寸640*640”后按照trtexec执行命令时出现segmentation fault，请问为啥会出现这个内存不够的问题呢？修改batch大小也还是报同样的错。期待您的回复！
执行命令如下：trtexec --onnx=yolov3_new_dynamic.onnx --explicitBatch --optShapes=000_net:16x3x640x640 --maxShapes=000_net:32x3x640x640 --minShapes=000_net:1x3x640x640 --shapes=000_net:16x3x640x640 --saveEngine=yolov3_dynamic.engine
![image](https://user-images.githubusercontent.com/23280661/113402888-5d272e80-93d8-11eb-8862-15e84d51e555.png)

**Comment by MAhaitao999** [comment]
> 您好，感谢您的工程！按照操作对“修改了网络结构及输入图片尺寸640*640”后按照trtexec执行命令时出现segmentation fault，请问为啥会出现这个内存不够的问题呢？修改batch大小也还是报同样的错。期待您的回复！
> 执行命令如下：trtexec --onnx=yolov3_new_dynamic.onnx --explicitBatch --optShapes=000_net:16x3x640x640 --maxShapes=000_net:32x3x640x640 --minShapes=000_net:1x3x640x640 --shapes=000_net:16x3x640x640 --saveEngine=yolov3_dynamic.engine
> ![image](https://user-images.githubusercontent.com/23280661/113402888-5d272e80-93d8-11eb-8862-15e84d51e555.png)

把你模型发给我看一下

**Comment by Jaiy** [comment]
@MAhaitao999 感谢回复，我这边查到错误啦，是cfg以及转换onnx时的问题

**Comment by graysuki** [comment]
能详细说下什么问题吗
